version: '3'

services:
  api:
    container_name: course-api
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/coursedb
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    container_name: course-mongodb
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
